export const step1Categories = [
  'Microbiology',
  'Immunology',
  'Histology',
  'Anatomy',
  'Physiology',
  'Embryology',
  'Biochemistry',
  'Genetics',
  'General Pathology',
  'Genreal Pharmacology',
  'Behavioral sciences',
  'Biostatistics and epidemiology',
  'Ethics',
  'Cardiology',
  'Musculoskeletal',
  'Neurology',
  'Psychiatry',
  'Gastrointestinal',
  'OB/GYN',
  'Nephrology/Urology',
  'Dermatology',
  'Pulmonology',
  'Hematology/Oncology',
  'Endocrinology',
  'Ophthalmology',
]

export const step2Categories = [
  'Internal Medicine',
  'Surgery',
  'Pediatrics',
  'Obstetrics and Gynecology',
  'Psychiatry',
  'Preventive Medicine',
  'Family Medicine',
  'Emergency Medicine',
  'Radiology',
  'Dermatology',
  'Ophthalmology',
  'Otolaryngology',
  'Orthopedics',
  'Anesthesiology',
  'Geriatrics',
  'Ethics and Legal Issues in Medicine',
  'Ethics',
  'Cardiology',
  'Musculoskeletal',
  'Neurology',
  'Psychiatry',
  'Gastrointestinal',
  'OB/GYN',
  'Nephrology/Urology',
  'Dermatology',
  'Pulmonology',
  'Hematology/Oncology',
  'Endocrinology',
  'Ophthalmology',
]

export const step3Categories = [
  'Internal Medicine',
  'Surgery',
  'Pediatrics',
  'Obstetrics and Gynecology',
  'Psychiatry',
  'Preventive Medicine',
  'Family Medicine',
  'Emergency Medicine',
  'Radiology',
  'Dermatology',
  'Ophthalmology',
  'Otolaryngology',
  'Orthopedics',
  'Anesthesiology',
  'Geriatrics',
  'Ethics and Legal Issues in Medicine',
  'Ethics',
  'Cardiology',
  'Musculoskeletal',
  'Neurology',
  'Psychiatry',
  'Gastrointestinal',
  'OB/GYN',
  'Nephrology/Urology',
  'Dermatology',
  'Pulmonology',
  'Hematology/Oncology',
  'Endocrinology',
  'Ophthalmology',
]
